Models/Dentist/DentistDetails.cs
namespace Dental_Clinic.Models
{
    public class DentistDetails
    {
        public DentistDetails() { }
        public DentistDetails(Dentist dentist)
        {
            this.Id = dentist.Id;
            this.FirstName = dentist.FirstName;
            this.LastName = dentist.LastName;
            this.Description = dentist.Description;
        }


        public ulong Id { get; set; }
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? Description { get; set; }
    }
}

Models/Dentist/DentistForm.cs
namespace Dental_Clinic.Models
{
    public class DentistForm
    {
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? Description { get; set; }
    }
}

Controllers/DentistController.cs
using Dental_Clinic.Models;
using Dental_Clinic.Repositories;
using Dental_Clinic.Repositories.Impl;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Dental_Clinic.Controllers
{
    [Route("dentists")]
    public class DentistController : Controller
    {

        private readonly IDentistRepository _dentistRepository;

        public DentistController(dentalclinicContext context)
        {
            _dentistRepository = new DentistRepository(context);
        }

        [Route("")]
        public IActionResult Index()
        {
            List<DentistDetails> dentistDetails = new List<DentistDetails>();
            _dentistRepository.GetAll().ForEach(d => dentistDetails.Add(new DentistDetails(d)));


            return View(dentistDetails);
        }

        [Route("{id?}")]
        public IActionResult Details(ulong id)
        {
            var fetched = _dentistRepository.Get(id);

            if(fetched == null)
            {
                Response.StatusCode = 404;
                var errorMessage = new ErrorViewModel
                {
                    Message = "404 Not Found. " +
                    "We could not find a dentist with an id of " + id + "."

                };
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }


            var result = new DentistDetails(fetched);

            return View(result);
        }

        [Route("{id?}/patients")]
        public IActionResult Patients(ulong id)
        {
            List<PatientDetails> patientDetails = new List<PatientDetails>();
            _dentistRepository.Get(id).Patients.ToList().ForEach(p => patientDetails.Add(new PatientDetails(p)));

            return View("~/Views/Patient/Index.cshtml", patientDetails);
        }

        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create")]
        public IActionResult Create(IFormCollection collection)
        {

            Dentist entity = new Dentist();
            entity.FirstName = collection["FirstName"];
            entity.LastName = collection["LastName"];
            entity.Description = collection["Description"];

            _dentistRepository.Add(entity);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }


        [Route("delete/{id?}")]
        public IActionResult Delete(ulong id)
        {
            var entity = _dentistRepository.Get(id);
            var details = new DentistDetails(entity);

            if(entity == null)
            {
                Response.StatusCode = 404;
                var errorMessage = new ErrorViewModel
                {
                    Message = "404 Not Found. " +
                    "We could not find a dentist with an id of " + id + "."

                };
                return View("~/Views/Shared/Error.cshtml", errorMessage);
            }


            return View(details);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("delete/{id?}")]
        public IActionResult Delete(ulong id, IFormCollection collection)
        {
            _dentistRepository.Delete(id);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Dentist/Create.cshtml
@model Dental_Clinic.Models.DentistForm

@{
    ViewData["Title"] = "Create";
}

<h1>Create dentist account</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Dentist/Delete.cshtml
@model Dental_Clinic.Models.DentistDetails

@{
    ViewData["Title"] = "Delete dentist";
}


<h3>Are you sure you want to delete the account of this dentist?</h3>
<h3 class="text-danger">This action is irreversible!</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        @if (!String.IsNullOrEmpty(Model.Description))
        {
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        }
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Dentist/Details.cshtml
@model Dental_Clinic.Models.DentistDetails

@{
    ViewData["Title"] = $"{Model.FirstName} {Model.LastName}";
}
<h1>
    @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        @if (!String.IsNullOrEmpty(Model.Description))
        {
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>|
    @Html.ActionLink("Patients", "Patients", "Dentist", new { id=Model.Id })
</div>

Views/Dentist/Index.cshtml
@model IEnumerable<Dental_Clinic.Models.DentistDetails>

@{
    ViewData["Title"] = "List of all dentists";
}

<h1>Dentists</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Info", "Details", new {id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>